- README.md
@aitboudad I mentioned the http subscribe "issue" as I consider it important.
> add loading service doc to readme

- README.md
- packages/core/README.md
Some sample code was broken in the main & core readme file
> doc: fix sample code

- demo/src/app/app.component.html
- loading-bar.css
- packages/core/src/loading-bar.component.spec.ts
- packages/core/src/loading-bar.component.ts
> feat(core): allow change bar color

- packages/core/README.md
- packages/http-client/README.md
- packages/http-client/src/loading-bar.interceptor.ts
- packages/http/README.md
- packages/router/README.md
> fix(http-client): ensure request is closed on unsubscribe.

- packages/http/src/loading-bar.http.ts
> fix(http): fixed Infinite loading when using Observable.zip.

- README.md
"LoadingBarHttpClientModule.forRoot()" to "LoadingBarModule.forRoot()"
> Comment correction for core usage.

- demo/src/app/app.component.ts
- demo/src/app/hello.component.ts
- packages/core/src/loading-bar.component.ts
> fix: disable OnPush change detection.

- README.md
- packages/core/src/loading-bar.component.ts
> feat(core): allow setting height and diameter for loading bar/spinner.

- README.md
- packages/http-client/src/loading-bar.interceptor.ts
- packages/http/src/loading-bar.http.ts
> fix(http-client): ensure starting when using async interceptor.

- README.md
- packages/core/src/loading-bar.component.scss
- packages/core/src/loading-bar.component.ts
> feat(code): allow setting loading inside a container instead of the top-screen.

- demo/src/app/app.component.html
- demo/src/app/app.component.ts
- packages/core/src/loading-bar.service.spec.ts
- packages/core/src/loading-bar.service.ts
> feat(core): make set and increment public + allow setting inital value for start.

- demo/src/app/app.component.html
- demo/src/app/app.component.ts
- package-lock.json
- package.json
> docs: add example that show loader when a request has taken more than 500ms.

- demo/src/app/app.component.html
- demo/src/app/app.component.ts
- packages/core/src/loading-bar.service.spec.ts
- packages/core/src/loading-bar.service.ts
> feat(core): add stop method to force close the loader

- packages/core/src/loading-bar.component.ts
> fix(core): set view encapsulation to emulated

- packages/core/src/loading-bar.component.scss
> feat: 🎸 add RTL support

- packages/core/package.json
> fix(core): move tslib to direct dependencies

- packages/core/src/loading-bar.service.spec.ts
- packages/core/src/loading-bar.service.ts
- packages/core/src/loading-bar.state.ts
- packages/http-client/src/http.module.ts
> fix(core): take account of state updates during intitial render

- README.md
- demo/src/app/app.component.ts
- packages/core/src/loading-bar.config.ts
- packages/core/src/loading-bar.service.ts
- packages/core/src/loading-bar.state.ts
- packages/core/src/public_api.ts
> feat(core): add option to customise latency threshold

- packages/core/src/loading-bar.service.ts
> fix(core): detect changes of actions outside zones

- README.md
Thanks for this great lib!
I had a bit of trouble bringing it into a new project, and wanted to document the config that made it go.
> docs: update readme with standalone example for http
